/* DBAL_TABLENAME_BEGIN  */
/* DBAL_TABLENAME_END */
DROP TABLE IF EXISTS ;
CREATE TABLE  (
  id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
