<?php
/*
 * Drops and rebuilds the test database from scratch on every run, so
 * every functional test starts from a known, empty, current-schema
 * state -- no leftover rows from a previous run, no drift between the
 * schema tests run against and the schema web/classes/yaml/*.yaml
 * actually describes today.
 *
 * This is also, deliberately, the single most dangerous operation in
 * the whole test suite (DROP DATABASE), so every safety check this
 * class can re-assert, it does -- see reset()'s own comments.
 */
class TestSchema {
    private static bool $didReset = false;

    /**
     * Regenerates the entity class PHP files (patientsClass,
     * appointmentsClass, ...), bootstrap_classes.php, and the DDL under
     * <dir>/sql/*.sql from <dir>/yaml/*.yaml via zeusfw's maker.php -- the
     * exact same commands a developer runs by hand for a normal checkout
     * (see tests/README.md). Regenerating on every run, rather than
     * committing a schema fixture, means the suite always tests against
     * today's actual schema and doubles as a consistency check in its own
     * right: a broken/renamed YAML field, or a maker.php upstream change,
     * fails loudly here instead of silently drifting from what's really
     * deployed.
     *
     * Must run BEFORE the framework bootstrap is required (bootstrap.php
     * calls this first, ahead of `require_once __FWDIR__ .
     * '/bootstrap.php'`) -- that require is what pulls in
     * web/classes/bootstrap_classes.php, which fatals immediately on a
     * fresh checkout where these generated files don't exist yet.
     */
    static function regenerateClasses(string $fwDir, string $appDir): void {
        self::regenerateClassFiles($fwDir . '/classes', $fwDir, 'framework');
        self::regenerateClassFiles($appDir . '/web/classes', $fwDir, 'application');
    }

    /** Every functional test's setUp should call this before writing anything. */
    static function assertSafeToMutate(): void {
        if (!self::$didReset) {
            zpms_test_fatal('TestSchema::reset() must run before any functional test -- see tests/run_all.php.');
        }

        $row = dbConnection::getConnection()
            ->query("SELECT COUNT(*) AS c FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = '_test_suite_marker'")
            ->fetch();

        if (!$row || (int)$row['c'] !== 1) {
            zpms_test_fatal(
                "_test_suite_marker table not found in " . DB_NAME . ".\n" .
                "       This database was not (or no longer is) prepared by TestSchema::reset() --\n" .
                "       refusing to run any test that writes data against it."
            );
        }
    }

    /**
     * DROPs and recreates DB_NAME, then loads the (already regenerated by
     * regenerateClasses(), above) schema SQL into it fresh. Requires a live
     * dbConnection, so this runs after the framework bootstrap, unlike
     * regenerateClasses().
     */
    static function reset(): void {
        // Re-assert the "test" guard immediately before the drop, independent
        // of bootstrap.php's own check -- this is the actual point of no
        // return, so it gets its own, un-skippable check right here.
        if (stripos(DB_NAME, 'test') === false) {
            zpms_test_fatal('DB_NAME does not contain "test" -- refusing to DROP DATABASE.');
        }

        echo "Rebuilding test database " . DB_NAME . "...\n";

        // A fresh, dbname-less connection for the DROP/CREATE themselves --
        // the app's own dbConnection is already bound to DB_NAME, and MySQL
        // (via PDO) can drop the database a connection currently has
        // selected, but a separate admin-level connection keeps this step's
        // intent explicit rather than relying on that being true.
        $admin = new PDO('mysql:host=' . DB_HOST, DB_USER, DB_PASS);
        $admin->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $quotedName = str_replace('`', '``', DB_NAME);
        $admin->exec("DROP DATABASE IF EXISTS `$quotedName`");
        $admin->exec("CREATE DATABASE `$quotedName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $admin = null;

        self::loadSchemaSql(__FWDIR__ . '/classes/sql', 'framework');
        self::loadSchemaSql(ZPMS_TEST_APPDIR . '/web/classes/sql', 'application');

        dbConnection::getConnection()->exec(
            'CREATE TABLE _test_suite_marker (created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)'
        );
        dbConnection::getConnection()->exec('INSERT INTO _test_suite_marker () VALUES ()');

        self::$didReset = true;
        echo "Test database ready.\n";
    }

    private static function regenerateClassFiles(string $classDir, string $fwDir, string $label): void {
        if (!is_dir($classDir . '/yaml')) {
            zpms_test_fatal("$classDir/yaml not found -- can't regenerate the $label schema.");
        }

        $makerPhp = escapeshellarg($fwDir . '/maker/maker.php');
        $prefix = 'cd ' . escapeshellarg($classDir) . ' && php ' . $makerPhp . ' ';

        exec($prefix . 'spill:class:all 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            zpms_test_fatal("Generating $label entity classes failed:\n" . implode("\n", $output));
        }

        $output = [];
        exec($prefix . 'update:bootstrap 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            zpms_test_fatal("Regenerating $label bootstrap_classes.php failed:\n" . implode("\n", $output));
        }

        $output = [];
        exec($prefix . 'spill:sql:all 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            zpms_test_fatal("Generating $label SQL failed:\n" . implode("\n", $output));
        }

        echo "  regenerated $label entity classes\n";
    }

    private static function loadSchemaSql(string $sqlDir, string $label): void {
        $sqlFiles = glob($sqlDir . '/*.sql');
        if (!$sqlFiles) {
            zpms_test_fatal("No $label *.sql files found in $sqlDir -- did regenerateClasses() run first?");
        }
        sort($sqlFiles);

        $pdo = dbConnection::getConnection();
        foreach ($sqlFiles as $file) {
            $sql = file_get_contents($file);
            if ($sql === false || trim($sql) === '') {
                zpms_test_fatal("Could not read generated SQL file: $file");
            }
            try {
                $pdo->exec($sql);
            } catch (PDOException $e) {
                zpms_test_fatal("Loading $label schema file " . basename($file) . " failed: " . $e->getMessage());
            }
        }
        echo "  loaded " . count($sqlFiles) . " $label table(s)\n";
    }
}
