title: Patient Management System

tz: "Europe/Athens"

meta:
  - charset="UTF-8"
  - http-equiv="X-UA-Compatible" content="IE=edge"
  - name="viewport" content="width=device-width, initial-scale=1.0"

# favicon: 'assets/favicon.ico'
favicon:
  type: image/png
  src: assets/logo3.png

templates:
  - './core/templates/'
  - './templates/'
  - './modules/finance/templates/'

css:
  - normalize:
    src: 'css/normalize.css'
  - navigation:
    src: 'css/navigation.css'
  - styles:
    src: 'css/styles.css'
  - boxicons:
    src: 'css/bx/css/boxicons.min.css'
  # - breadcrumbs:
    # src: 'css/breadcrumbs.css'
  # - utils:
    # src: 'css/loader.css'
  # - pikaday:
    # src: "https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"


# setup multiple language support
multilingual: true

languages:
  - en
  - gr

# use libraries concept to attach different css/js to different pages
libraries:
  loader-library:
    css:
      - loader:
        src: 'css/loader.css'
    foot_script:
      - loader:
        type: "text/javascript"
        src: 'js/loader.js'
    # - head_script:
  # location-places:
    # css:
    #   - location:
    #     src: 'css/location.css'
    # foot_script:
    #   - location:
    #     type:
    #     src: 'js/location.js'
  # breadcrumbs-library:
    # css:
      # - breadcrumbs:
        # src: 'css/breadcrumbs.css'
  qrgenerator-library:
    css:
      - qrgen:
        src: 'css/qrgenerator.css'
  textarea-autoexpand-library:
    foot_script:
      - textarea-autoexpand:
        defer:
        type: "text/javascript"
        src: 'js/textarea-autoexapand.js'
  pikaday-library:
    css:
      - pikaday_css:
        type: 'text/css'
        src: 'https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css'
    head_script:
      - pikaday_js:
        type: "text/javascript"
        src: "https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"
        # defer:
      - moment_js:
        type: "text/javascript"
        src: "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.30.1/moment-with-locales.min.js"
        # defer:
    foot_script:
      - pikaday_js:
        type:
        src: "."


# head_script:

foot_script:
  - scripts:
    type: "text/javascript"
    src: "js/scripts.js"
    defer: 
  # - loader:
    # type:
    # src: "js/loader.js"
  
roles:
  anonymous: anonymous
  administrator: all
  authenticated: authenticated_content
  user: [patients-view-list, appointments-view-list]
  power-user: [
    patients-view-list,
    patients-new-patient,
    patients-delete-patient, 
    patients-edit-patient, 
    appointment-edit,
    pdflib-access,
    operations-view-list,
    operations-new-operation,
    operations-delete-operation,
    operations-edit-operation
    ]


# reduce analytics entries, by not logging localhost calls
analytics:
  ignore_ips: []
  # [127.0.0.1]

routes:
  homepage:
    title: 
      gr: "Αρχική"
      en: "Homepage"
    name: homepage
    url: "/"
    handler: homepage
#  admin:
#    title: "Administration"
#    name : admin
#    url: "/admin"
#    handler: admin
#    access: administrator
  login:
    title:
      en: "User login"
      gr: "Είσοδος χρήστη"
    url: "/login"
    handler: login
    method: get
  login_post:
    title:
      en: "User login"
      gr: "Είσοδος χρήστη"
    url: "/login"
    handler: login_post
    method: post
  logout:
    title: "User logout"
    url: "/logout"
    handler: logout
  settings:
    title: 
      gr: "Ρυθμίσεις"
      en: "Settings"
    url: "/settings"
    handler: settings
  applications:
    title: 
      gr: "Εφαρμογές"
      en: "Applications"
    url:
    handler:
  patients:
    title:
      gr: "Ασθενείς"
      en: "Patients"
    url:
  patients_list:
    title: 
      gr: "Λίστα ασθενών"
      en: "Patients List"
    url: [
          "/patients",
          "/patients/sort/{key}",
          "/patients/sort/{key}/{order}"
          ]
    handler: patients_list
    access: authenticated user
  patients_search:
    title: "Patients"
    url: "/patients/search/{term}"
    handler: patients_list_search
    access: authenticated user
  # patients_search0:
    # title: "Patients"
    # url: "/patients/search"
    # handler: patients_list
    # access: authenticated user
  patients_search_ajax:
    title: 
      gr: "Ασθενείς"
      en: "Patients"
    url: "/patients/searchajax/{term}"
    handler: patients_list_search_ajax
    access: authenticated user
  patients_search_post:
    title: "Patients search"
    url: "/patients/search"
    handler: patients_search_post
    method: post
  patient_edit:
    title: 
      en: "Patient edit"
      gr: "Επεξεργασία ασθενή"
    url: "/patient/{id}/edit"
    handler: patient_edit
    method: get
  patient_edit_post:
    title: "Patient edit"
    url: "/patient/{id}/edit"
    handler: patient_edit_post
    method: post
  patient_new:
    title: 
      en: "New Patient"
      gr: "Νέος ασθενής"
    url: /patient/new
    handler: patient_new
    method: get
  patient_new_post:
    title: "New Patient"
    url: /patient/new
    handler: patient_new_post
    method: post
  patient_delete:
    title: "Patient delete"
    url: "/patient/{id}/delete"
    handler: patient_delete
  appointments:
    title:
      gr: "Εφαρμογές"
      en: "Appointments"
    url: /appointments
    handler: appointments_list
    # access: authenticated user
  appointment_edit:
    title:
      gr: "Επεξεργασία ραντεβού"
      en: "Appointment edit"
    url: "/appointment/{id}/edit"
    handler: appointment_edit
    method: get
  appointment_edit_post:
    title: "Appointment edit"
    url: "/appointment/{id}/edit"
    handler: appointment_edit_post
    method: post
  appointment_new:
    title:
      gr: "Νέο ραντεβού"
      en: "New appointment"
    url: "/appointment/new"
    handler: appointment_new
    method: get
  appointment_new_post:
    title: "New appointment"
    url: "/appointment/new"
    handler: appointment_new_post
    method: post
  appointment_delete:
    title: "Appointment delete"
    url: "/appointment/{id}/delete"
    handler: appointment_delete
  appointment_recover:
    title: "Appointment recover"
    url: "/appointment/{id}/recover"
    handler: appointment_recover
  patient_appointment_new:
    title: "New patient appointment"
    url: "/appointment/{id}/newappointment"
    handler: patient_appointment_new
    method: get
  patient_appointment_new_post:
    title: "New patient appointment"
    url: "/appointment/{id}/newappointment"
    handler: patient_appointment_new_post
    method: post
  qrgenerator:
    title:
      gr: "Δημιουργία κωδικού QR"
      en: "Generate QR code"
    url: "/apps/genqr"
    handler: app_generate_qr
    method: get
  qrgenerator_post:
    title: "Generate QR code"
    url: "/apps/genqr"
    handler: app_generate_qr
    method: post
  clinics_form:
    title: "Edit clinics form"
    url: "/apps/edit_clinics"
    handler: clinics_edit
    method: get
  webforms_post:
    title: "Process Webform"
    url: "/webform/processform/{guid}"
    handler: formsClass::processform
    method: post
  webforms_view:
    title: "View Webform"
    url: "/webform/viewform/{formname}"
    handler: formsClass::viewform
  totp_management:
    title: "Activate TOTP"
    url: "/totp/{action}"
    handler: totp_handler
  operations_list:
    title: 
      gr: "Λίστα χειρουργείων"
      en: "Operations List"
    url: [
          "/operations",
          "/operations/sort/{key}",
          "/operations/sort/{key}/{order}"
          ]
    handler: operations_list
    access: authenticated user
  operations_search:
    title: "Οperations"
    url: "/operations/search/{term}"
    handler: operations_list_search
    access: authenticated user
  # operations_search0:
    # title: "operations"
    # url: "/operations/search"
    # handler: operations_list
    # access: authenticated user
  operations_search_ajax:
    title: 
      gr: "Χειρουργεία"
      en: "Operations"
    url: "/operations/searchajax/{term}"
    handler: operations_list_search_ajax
    access: authenticated user
  operations_search_post:
    title: "operations search"
    url: "/operations/search"
    handler: operations_search_post
    method: post
  operation_edit:
    title: 
      en: "Operation edit"
      gr: "Επεξεργασία χειρουργείoυ"
    url: "/operation/{id}/edit"
    handler: operation_edit
    method: get
  operation_edit_post:
    title: "operation edit"
    url: "/operation/{id}/edit"
    handler: operation_edit_post
    method: post
  operation_new:
    title: 
      en: "New operation"
      gr: "Νέο χειρουργείο"
    url: /operation/new
    handler: operation_new
    method: get
  operation_new_post:
    title: "New operation"
    url: /operation/new
    handler: operation_new_post
    method: post
  operation_delete:
    title: "operation delete"
    url: "/operation/{id}/delete"
    handler: operation_delete


regions:
  - header
  - main_navigation
  - notification
  - main_content
  - footer

# blocks:
#   - header: header
#   - breacrumbs: header
#   - mainnavigation: main_navigation
#   - maincontent: main_content
#   - footer: footer

# structure example (updated)
# structure:
#   region1:
#     - block1
#     - section1:
#       - block2
#       - block3
#     - section2:
#       - block4
#       - section3:
#         - block5
#       - block6
#     - block7
#   region2:
#
structure:
  header:
    - header
    - header-grid-2x1:
      - left-column:
        - userblock
      - right-column:
        - githash
        - language_selector
    - location
    - breadcrumbs
  main_navigation:
    - mainnavigation
  notification:
    - notifications
    - message
  main_content:
    - content
  footer:
    - footer
    - copyright

menu:
  main:
    - homepage:
      text: 
        gr: 'Αρχική'
        en: 'Home'
      url: '/'
      # path: home
    - patients:
      text: 
        gr: 'Ασθενείς'
        en: 'Patients'
      access: power-user
      # url: '/patients'
      submenu:
        - patients_list:
          text: 
            gr: 'Λίστα'
            en: 'List'
          url: '/patients'
        - patient_new:
          text: 
            gr: 'Νεός'
            en: 'New'
          url: /patient/new
      # path: '/patients'
    - operations:
      text:
        gr: 'Χειρουργεία'
        en: 'Operations'
      access: power-user
      # url: '/operations'
      submenu:
        - operations_list:
          text: 
            gr: 'Λίστα'
            en: 'List'
          url: '/operations'
        - patient_new:
          text: 
            gr: 'Νέο'
            en: 'New'
          url: /operation/new
      # path: '/patients'
      # disabled: true
    - appointments:
      text:
        gr: 'Ραντεβού'
        en: 'Appointments'
      url: '/appointments'
      disabled: true
    - applications:
      text:
        en: 'Apps'
        gr: 'Εφαρμογές'
      submenu:
        - settings:
          text:
            gr: "Ρυθμίσεις"
            en: "Settings"
          url: '/settings'
          access: power-user
        - contact:
          text:
            gr: 'Επικοινωνία'
            en: 'Contact'
          url: '#'
        - qrgenerator:
          text:
            gr: 'Δημιουργία κωδικού QR'
            en: 'Generate QR code'
          url: /apps/genqr
        - pdflib-module:
          text:
            gr: 'Καταχωρητήριο PDF'
            en: 'PDF Archive'
          url: /apps/pdflib
          access: power-user
        - finance-module:
          text:
            gr: 'Οικονομικά Στοιχεία'
            en: 'Finanace'
          url: /apps/finance

# Module site configuration
#
# modfconf:
#   module_name:
#     hide: (hide module from these routes)
#     display: (display module in these routes)
#       route_name:
#         arguments: (arguments to pass by default)
#           - arg1: value1
#         access: [access_roles, to allow for route]
modconf:
  message:
    display:
      userprofile:
          arguments:
            type: "Announcements"
          access: authenticated
      

modules:
  path:
    - "/web/core/modules/"
    - "/web/modules/"
  modules:
    - admin
    - mainnavigation
    - notifications
    - header
    - breadcrumbs
    - userblock
    - userprofile
    - htmltext
    - githash
    - copyright
    - content
    - location
    - datepicker
    - pdflib
    - language_selector
    - message
    - finance
