<?php
/* `php -l` across every PHP file this repo actually owns. Excludes
 * web/core (the vendored zeusfw framework -- a symlink, and someone
 * else's repo/test concern) and web/classes/*.php (generated by
 * maker.php from web/classes/yaml/*.yaml on every test run -- if THAT
 * generation step produces broken PHP, TestSchema::regenerateClasses()
 * already fails loudly and separately; this check is about source files
 * a person actually edits). */

function zpms_static_php_lint(TestRunner $runner): void {
    $root = ZPMS_TEST_APPDIR;

    $patterns = [
        $root . '/web/*.php',
        $root . '/web/modules/*/*.php',
        $root . '/web/modules/*/*/*.php',
        $root . '/bin/*.php',
        $root . '/tests/*.php',
        $root . '/tests/lib/*.php',
        $root . '/tests/static/*.php',
        $root . '/tests/functional/*.php',
    ];

    $files = [];
    foreach ($patterns as $pattern) {
        foreach (glob($pattern) as $file) {
            $files[$file] = true;
        }
    }
    // web/classes/*.php is matched by the `web/*.php` glob above -- drop it
    // explicitly (glob's own patterns can't express "not this subdirectory").
    foreach (array_keys($files) as $file) {
        if (str_starts_with($file, $root . '/web/classes/')) {
            unset($files[$file]);
        }
    }

    ksort($files);
    assert_true(count($files) > 0, 'no PHP files were found to lint -- check the glob patterns above');

    foreach (array_keys($files) as $file) {
        $rel = substr($file, strlen($root) + 1);
        $runner->add("php -l $rel", function () use ($file, $rel) {
            $output = [];
            $exitCode = 0;
            exec('php -l ' . escapeshellarg($file) . ' 2>&1', $output, $exitCode);
            assert_equal(0, $exitCode, "$rel:\n" . implode("\n", $output));
        });
    }
}
